workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Grant execute permission for gradlew
        script: chmod +x android/gradlew || echo "gradlew not found, creating it..."
flutter pub get
      - name: Build Android App (APK)
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
