workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Grant execute permission for gradlew
        script: chmod +x android/gradlew
      - name: Build Android App (APK)
        script: cd android && ./gradlew assembleDebug
    artifacts:
      - build/outputs/apk/**/*.apk
